### ISSUE TITLE
Fail processing or at least add warning when a required environment variable is not resolved

### ISSUE THREAD

**Issue by goldmann** [containers-tools/cct#11]
Currently we try to process module even if the variables are not resolved.

**Comment by vpavlin** [comment]
IIUC You are referring to this: https://github.com/containers-tools/cct/wiki/Environment-variables

But from `if neither of previous step is true $FOO is passed to module as a text $FOO` I'd say it's ok to have non-resolvable variables..

**Comment by rwngwn** [comment]
yep. @goldmann  on IRC suggested that if you want to pass variables you should escape t like \$FOO. 
So maybe its better this way, because we can  warn about typos in un-escaped variable names which should be resolved correctly. But this is still in discussion.

**Comment by rwngwn** [comment]
this checking should be nice in some future version
