### ISSUE TITLE
Descriptor file language selection

### ISSUE THREAD

**Issue by goldmann** [containers-tools/cct#4]
The current proposal is to use YAML, because of two reasons:
1. It's simple to read by human
2. It's already proven to do the job (hint: Ansible)

Since this tool is meant to have all login in modules (plugins) the goal for the descriptor file is to execute these plugins in a parametrized way, therefore we can focus on the readability of the descriptor file, because we don't need to put there a lot of specific things (like paths, specific values, etc). Another good feature of YAML is that we can easily (and it'll be still readable) define block of commands to be executed that provide atomic change (for example: add datasource definition to EAP).

Comments?

/cc @hhorak

**Comment by rwngwn** [comment]
actually, YAML file seems readable and usable for now - so i would stick with it without a really good reason to change.

**Comment by hhorak** [comment]
YAML seems fine, it gives enough flexibility and in python it's easy to work with. It get's complicated when somebody wants to implement some logic in the commands, like in devassistant it went to implementing own DSL in YAML. For the logic in cct there are the modules written in python, IIUIC, so it seems fine.

**Comment by vpavlin** [comment]
What would be alternatives? 

`JSON` is too machine oriented
`INI` does not provide simplicity for hierarchical data
`XML` hmm...nope:) 
Anything else which is common enough so that people don't have to learn language they haven't seen yet?

**Comment by rwngwn** [comment]
its yaml for a long time.
