### ISSUE TITLE
The chksum key should be renamed md5sum or checksum and have sub-keys

### ISSUE THREAD

**Issue by jmtd** [containers-tools/cct#44]
This is basically the same issue as https://github.com/jboss-dockerfiles/dogen/issues/13 . All the same arguments apply. IMHO I would like to see that resolved in dogen first, but then cct be consistent with dogen.

**Comment by rwngwn** [comment]
CCT is using alg:hash aproach now. It enables user to use any hash alg available in python hashlib module.
