### ISSUE TITLE
command line should take precedence over environment variable

### ISSUE THREAD

**Issue by jmtd** [containers-tools/cct#53]
If you define CCT_CHANGES=<some file>, but then run cct as

```
RUN CCT_MODULES_PATH=/tmp/cct/ cct -v  /tmp/cct/cct.yaml
```

The instructions in `/tmp/cct/cct.yaml` are ignored and the file named in `CCT_CHANGES` is executed.

I think if changes are supplied via command-line they should always be executed.

**Comment by rwngwn** [comment]
This is intended behavior because if cct is used as an entrypoint for runtime configuration this enables you to override stuff via CCT_CHANGES. Maybe we can do something like CCT_CHANGES_APPEND or some way to say that you dont wont to override stuff.

**Comment by jmtd** [comment]
I see. The problem I have is I can't set CCT_CHANGES with dogen (to specify run time actions) because that will be included in the template before CCT is ran for build time actions. Maybe the dogen CCT plugin could insert the ENV after build time run; or maybe there's another approach we can use.

**Comment by jmtd** [comment]
I've worked around this problem in dogen, so I'm not sure whether to just close this. I will for now.
