### ISSUE TITLE
Configration steps report

### ISSUE THREAD

**Issue by rwngwn** [containers-tools/cct#6]
After running the module we should create some easy to read and parse report of steps taken, and their statuses. This can be stored also in a Docker image for audit purposes.

**Comment by vpavlin** [comment]
s/Docker image/Docker container/ ... correct?

**Comment by rwngwn** [comment]
actually both. in container for run-time configuration and in image for build-time. Because if you have cct inside you can run in Dockerfile too.

**Comment by vpavlin** [comment]
Ah, correct..good point. How does this map to the module definition? Are you going to distinguish between build vs. runtime module types?

**Comment by rwngwn** [comment]
No. modules are completely same. Because you typically need similar stuff. Only real difference is that in run-time you will just use new --command parameter to run your desired program in container in a way like:

``` bash
cct --comand "/opt/eap/bin/standalone.sh -b 0.0.0.0" -- eap.yaml
```

so this will just process all changes in eap.yaml file and then it will just start eap.
now its implemented like:  https://github.com/containers-tools/cct/blob/master/cct/cli/main.py#L48. 
Will document it tomorrow :)

**Comment by vpavlin** [comment]
Not that it matters much, but from UX point of view, I 'd probably more expect something like:

```
cct eap.yaml -- /opt/eap/bin/standalone.sh -b 0.0.0.0
```

So that I don't have to care about escaping issues with the command arguments..although I am not entirely sure how hard it would be to define this in ArgParser

**Comment by rwngwn** [comment]
yep, will  look more at ArgParser.. but it maybe hard because you can do stuff like

``` bash
cct foo.yaml bar.yaml baz.yaml
```

so you can process multiple yaml files. But wil try to make better syntax. This was just implement to us to be able to really start using it in our images.
