### ISSUE TITLE
Error handling

### ISSUE THREAD

**Issue by rwngwn** [containers-tools/cct#7]
CCT still lacks error handling, so there is a need to implement in and maybe we need some extension yaml file like saying that step should run:
- every time
- if something failed
- if all succeeded 

or at least stop execution of other steps.

**Comment by goldmann** [comment]
Currently we should fail if any of the steps fail, let's start with it. This will be simple enough to implement and we'll see later if we need something more.

**Comment by vpavlin** [comment]
I like what @TomasTomecek has in Dock plugins - something like `can_fail` which basically says: "if this fails, log it, ignore it and go on"  - would it make sense to have it also here?

**Comment by TomasTomecek** [comment]
@vpavlin: @goldmann suggested to rename that option: https://github.com/DBuildService/dock/issues/92 See also https://github.com/DBuildService/dock/issues/110

**Comment by vpavlin** [comment]
@TomasTomecek Ah, ok, good:) Anyway, you got  the point, I guess:-)

**Comment by rwngwn** [comment]
@vpavlin great idea. will implement it. But maybe will try to do it in some decorator. its maybe more readable than property. 
But for now, we are just failing on first error.

**Comment by rwngwn** [comment]
CCT changed its scope - and we are failing all the time - its primary for building a container - so if something fail, build fails.
