### ISSUE TITLE
Modules should be registered in cct at sartup

### ISSUE THREAD

**Issue by goldmann** [containers-tools/cct#8]
Additionally all options in the modules should be provided to cct so it could print usage instructions. We would need to support something like `cct MODULE --help` where it would print all the information about expected parameters and what is possible.

Another call, like `cct --list-modules` should be implemented to list all available modules.

**Comment by rwngwn** [comment]
We are already half a way through this.. we now support --list and --show option. So --list list all supported modules and --show <module> prints supported operations in a module.

**Comment by rwngwn** [comment]
Modules now can show help via --show MODULE options. eefa4329e6e7c785cbb61b50459861a85b9760d
