### ISSUE TITLE
Release module as part of CCT release

### ISSUE THREAD

**Issue by goldmann** [containers-tools/cct#92]
It would be good to create a module and attach it to the release page, as a download, so other tools like Dogen could fetch it and use directly without any changes. This would take the tag and apply any changes to it, so that the resulting zip would be consumable. Additionally this zip would contain all dependencies (like fat jar).

@dbecvarik WDYT? It would simplify Dogen's installing of CCT and we would not care about deps.

**Comment by rwngwn** [comment]
+1 on it. Actually I was thinking about it. And also with this I would like
to review and minimize cct dependencies.

**Comment by goldmann** [comment]
Great, thanks!

**Comment by rwngwn** [comment]
fixed by #93
